version: 2
updates:
  # Enable updates of git submodules
  - package-ecosystem: "gitsubmodule"
    # Look for submodules in root directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    assignees:
      - "ped7g"
    rebase-strategy: "disabled"
