task:
  name: windows mingw32 build
  env:
    CIRRUS_CLONE_DEPTH: 1
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 2
  build_script: ContinuousIntegration\winbuild_mingw32.bat
  sjasmplus_exe_existence_script: c:\tools\sjasmplus\sjasmplus --help
  assemble_examples_script: ContinuousIntegration\winbuild_mingw32_examples.bat
  assemble_tests_script: ContinuousIntegration\winbuild_mingw32_tests.bat

task:
  name: windows Visual Studio 15 2017 build
  env:
    CIRRUS_CLONE_DEPTH: 1
  windows_container:
    image: cirrusci/windowsservercore:cmake
    os_version: 2019
    cpu: 2
  build_script: ContinuousIntegration\winbuild_vs15_2017.bat
  # exe is installed at the same location as the MinGW build does
  sjasmplus_exe_existence_script: c:\tools\sjasmplus\sjasmplus --help
  assemble_examples_script: ContinuousIntegration\winbuild_mingw32_examples.bat
  assemble_tests_script: ContinuousIntegration\winbuild_mingw32_tests.bat
